In [307]:
#KNN классификатор для задачи многоклассовой классификации

import numpy as np

class KNN_classifier:
  def __init__(self, n_neighbors: int, **kwargs):
    self.K = n_neighbors

  def fit(self, x: np.array, y: np.array):

    self.data = x
    self.labels = y
  pass

  def predict(self, x: np.array):
    
    predictions = []
    labeled_distances = []
    
    for i in range(x.shape[0]):
      distances_row = []
      for j in range(self.data.shape[0]):
        distances_row.append((np.linalg.norm(x[i] - self.data[j]),self.labels[j]))
      labeled_distances.append(distances_row)

    sorted_lst = []
    for i in range(len(labeled_distances)):
        sorted_lst.append(list(sorted(labeled_distances[i])))
    for i in range(len(sorted_lst)):
       labels_count = {}
       for el in sorted_lst[i][0:self.K]:
         if el[1] in labels_count:
           labels_count[el[1]] += 1
         else:
           labels_count[el[1]] = 1 
       predictions.append(max(labels_count, key=labels_count.get))
    predictions = np.array(predictions)

    return predictions

In [308]:
X = np.array([[ 0.56510722,  0.68599596, -0.92388505, -0.29546048, -0.12437532],
       [-0.79617537,  0.98406791,  1.19542652, -0.05626863, -0.69868076],
       [ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685],
       [ 0.24671269, -0.41624448,  0.81679337,  1.59227446,  0.16192583],
       [-0.36972363,  0.17425997,  1.33668078,  1.16687907,  0.31709134],
       [-1.30482844, -0.05354323, -0.88862186, -1.121785  , -0.78442809],
       [-0.53975018,  0.90074877, -1.09317408,  1.52989481, -0.43375015],
       [-0.64709803, -0.09775791,  1.3506503 , -1.46957788,  1.63325543],
       [-0.73858464, -0.60678229,  0.31420272, -0.43100129, -0.37665876],
       [-0.29208809, -0.68795722,  0.06586655,  0.9583851 ,  1.70640775]])
X

array([[ 0.56510722,  0.68599596, -0.92388505, -0.29546048, -0.12437532],
       [-0.79617537,  0.98406791,  1.19542652, -0.05626863, -0.69868076],
       [ 0.9629688 , -1.00423925, -0.53842833, -0.23744358,  0.83226685],
       [ 0.24671269, -0.41624448,  0.81679337,  1.59227446,  0.16192583],
       [-0.36972363,  0.17425997,  1.33668078,  1.16687907,  0.31709134],
       [-1.30482844, -0.05354323, -0.88862186, -1.121785  , -0.78442809],
       [-0.53975018,  0.90074877, -1.09317408,  1.52989481, -0.43375015],
       [-0.64709803, -0.09775791,  1.3506503 , -1.46957788,  1.63325543],
       [-0.73858464, -0.60678229,  0.31420272, -0.43100129, -0.37665876],
       [-0.29208809, -0.68795722,  0.06586655,  0.9583851 ,  1.70640775]])

In [309]:
y = np.array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])
y

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [310]:
knn = KNN_classifier(n_neighbors=3)

In [311]:
knn.fit(X, y)

In [312]:
x_test = np.array([[-0.12489725,  0.65791923, -0.73112495,  1.42660225,  1.64728976],
       [ 0.01913388, -1.11351208, -0.63244098, -0.98121107,  0.38060892],
       [-0.92074931,  1.39812225,  0.39692147,  0.7717827 ,  0.44604002]])
x_test

array([[-0.12489725,  0.65791923, -0.73112495,  1.42660225,  1.64728976],
       [ 0.01913388, -1.11351208, -0.63244098, -0.98121107,  0.38060892],
       [-0.92074931,  1.39812225,  0.39692147,  0.7717827 ,  0.44604002]])

In [313]:
knn.predict(x_test)

array([1, 0, 0])